back/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import auth
from api.views import login
from api.views import main_page
from api.views import header
from api.views import fixed
from api.views import chart
from api.views import toggle
from api.views import page_config
from api.views import groups
from api.views import todo
from api.views import weight
from api.views import visited

api_router = routers.DefaultRouter()
api_router.register('group', groups.GroupViewSet, basename='group')
api_router.register('todo', todo.TodoViewSet, basename='task')
api_router.register('weight', weight.WeightViewSet, basename='weight')
api_router.register('visited', visited.VisitedViewSet, basename='visited')

urlpatterns = [
    path('auth/', auth.auth),
    path('demo/', auth.demo),
    path('csrf_setup/', login.csrf_setup),
    path('login/', login.LoginView.as_view()),
    path('logout/', auth.logout),
    path('main_page/', main_page.main_page),
    path('config/', page_config.PageConfigView.as_view()),
    path('header/', header.header),
    path('fixed/', fixed.fixed),
    path('chart/', chart.chart),
    path('group/<int:pk>/toggle_sub_group/', toggle.toggle_sub_group),
    path('todo/<int:pk>/extra/', todo.extra),

    path('', include(api_router.urls)),
]

back/family/urls.py
from django.urls import path
from family.views import pedigree, diagram, individual, examine
from task.const import APP_FAMILY

app_name = APP_FAMILY
urlpatterns = [
    path('', diagram.diagram_start, name='list'),
    path('<int:tree_id>/', diagram.diagram, name='diagram'),
    path('pedigree/', pedigree.PedigreeListView.as_view(), name='pedigree-list'),
    path('pedigree/import/', pedigree.import_tree, name='pedigree-import'),
    path('pedigree/<int:pk>/', pedigree.PedigreeDetailsView.as_view(), name='pedigree-detail'),
    path('pedigree/<int:pk>/export/', pedigree.export_tree, name='pedigree-export'),
    path('pedigree/<int:pk>/export/file/', pedigree.get_gedcom_file, name='pedigree-file'),
    path('pedigree/<int:pk>/examine/', examine.examine_tree, name='pedigree-examine'),
    path('<int:ft>/individual/@I<str:pk>@/<str:view>/', individual.IndividualDetailsView.as_view(), name='individual-detail'),
    path('<str:role>/<int:pk>/doc/<str:fname>/', pedigree.get_doc, name='doc'),
]

back/rok/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('api/', include('api.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('todo/', include('todo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from task.models import Group, Task, TaskGroup
from core.widgets import FileUpload, SwitchInput

#----------------------------------
class BaseCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name']

    def __init__(self, role, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.role = role
        
    def save(self, commit=True):
        ret = super().save(commit=False)
        ret.save()
        return ret

#----------------------------------
class BaseEditForm(forms.ModelForm):
    role = None

    upload = forms.FileField(
        label=_('Attachments'), 
        required=False, 
        widget=FileUpload())

    class Meta:
        model = Task
        fields = ['name']

    def __init__(self, role, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.role = role
        if ('grp' in self.fields):
            self.fields['grp'].initial = self.get_group_id()
            self.fields['grp'].choices = self.get_groups_hier(self.instance.user.id, role)

    def get_group_id(self):
        task_id = self.instance.id
        tgs = TaskGroup.objects.filter(task=task_id, role=self.role)
        if (len(tgs) > 0):
            tg = tgs[0]
            grp = tg.group
            return grp.id
        return None

    def get_groups_hier(self, user_id, role):
        groups = [(0, '----------'),]
        self.get_sorted_groups(groups, user_id, role)
        return groups

    def get_sorted_groups(self, groups, user_id, role, node=None, level=0):
        node_id = None
        if node:
            node_id = node.id
        items = Group.objects.filter(user=user_id, role=role, node=node_id).order_by('sort')
        for item in items:
            if (item.determinator != 'role') and (item.determinator != 'view'):
                groups.append((item.id, level * '—' + '  ' + item.name),)
                self.get_sorted_groups(groups, user_id, role, item, level+1)

    def clean_grp(self):
        ret = None
        grp_ok = int(self.cleaned_data['grp'])
        if grp_ok:
            parent = Group.objects.filter(node=grp_ok)
            if (len(parent) > 0):
                raise  ValidationError(_('A group must not have subgroups'))
            ret = Group.objects.filter(id=grp_ok).get()
        return ret

    def clean_categories(self):
        self.cleaned_data['categories'] = ' '.join([self.data['categories_1'], self.data['categories_2']]).strip()
        return self.cleaned_data['categories']


#----------------------------------
class CreateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

#----------------------------------
class GroupForm(forms.ModelForm):
    name = forms.CharField(
        label=_('Group name'),
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control mb-2'}),)
    node = forms.ChoiceField(
        label=_('Node'),
        widget=forms.Select(attrs={'class': 'form-control mb-2'}),
        choices=[(0, '------'),])
    completed = forms.BooleanField(
        label=False, 
        required=False, 
        widget=SwitchInput(attrs={'class': 'ms-1 mb-3', 'label': _('Display completed records')}))
    class Meta:
        model = Group
        fields = ['name', 'sort', 'node', 'completed']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-2', 'id': 'id_grp_name'}),
            'sort': forms.TextInput(attrs={'class': 'form-control mb-2'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if ('node' in self.fields):
            self.fields['node'].choices = self.get_node_hier(self.instance)

    def get_node_hier(self, group):
        groups = [(0, '----------'),]
        self.get_sorted_groups(groups, group.user.id, group.role, group.id)
        return groups

    def get_sorted_groups(self, groups, user_id, role, curr_id, node=None, level=0):
        node_id = None
        if node:
            node_id = node.id
        items = Group.objects.filter(user=user_id, role=role, node=node_id).order_by('sort')
        for item in items:
            if (item.id != curr_id) and (item.determinator != 'role') and (item.determinator != 'view'):
                groups.append((item.id, level * '—' + '  ' + item.name),)
                self.get_sorted_groups(groups, user_id, role, curr_id, item, level+1)

    def clean_node(self):
        ret = None
        node_ok = int(self.cleaned_data['node'])
        if node_ok:
            inst_id = self.instance.id
            node_id = node_ok
            test = Group.objects.filter(id=node_id).get()
            ret = test
            if (test.id == inst_id):
                raise  ValidationError(_('Self reference'))
            
            while test.node:
                node_id = test.node.id
                test = Group.objects.filter(id=node_id).get()
                if (test.id == inst_id):
                    raise  ValidationError(_('Loop link'))

            gts = TaskGroup.objects.filter(group=node_ok)
            if (len(gts) > 0):
                raise  ValidationError(_('Not empty node group'))

        return ret

back/family/views/base.py
import urllib, os, glob, re
from PIL import Image
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, FileResponse
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, UpdateView, FormMixin
from django.shortcuts import get_object_or_404
from core.context import Context
from core.dir_forms import UploadForm
from core.utils import extract_get_params
from family.models import FamTree, FamTreeUser, FamRecord, IndividualRecord, MultimediaRecord, RepositoryRecord, NoteStructure, SourceRecord, SubmitterRecord, Params
from task.const import APP_FAMILY


class GenealogyContext(Context):
    def get_dataset(self, group, query=None, nav_item=None):
        if group:
            if group.view_id == 'pedigree':
                return FamTreeUser.objects.filter(user_id=self.request.user.id)
            tree = Params.get_cur_tree(self.request.user)
            if not tree:
                return []
            tree_id = int(tree.id)
            match group.view_id:
                case 'family': return FamRecord.objects.filter(tree=tree_id)
                case 'media': return MultimediaRecord.objects.filter(tree=tree_id)
                case 'repo': return RepositoryRecord.objects.filter(tree=tree_id)
                case 'note': return NoteStructure.objects.filter(tree=tree_id)
                case 'source': return SourceRecord.objects.filter(tree=tree_id)
                case 'submitter': return SubmitterRecord.objects.filter(tree=tree_id)

        return []

    def get_app_context(self, user_id, search_qty=None, icon=None, nav_items=None, role=None):
        self.config.set_view(self.request)
        cur_tree = Params.get_cur_tree(self.request.user)
        title = cur_tree and cur_tree.name or 'Family tree'
        context = super().get_app_context(user_id, search_qty, icon, nav_items, title=title)
        if cur_tree:
            context['current_group'] = str(cur_tree.id)
        context['api_role'] = 'famtree'
        return context

class GenealogyListView(ListView, GenealogyContext, LoginRequiredMixin):

    def __init__(self):
        super().__init__()
        self.set_config(APP_FAMILY) #, 'tree')

    def get_context_data(self):
        context = super().get_context_data()
        self.config.set_view(self.request)
        upd_context = self.get_app_context(self.request.user.id, icon=self.config.view_icon)
        context.update(upd_context)
        if 'ft' in self.kwargs:
            tree_id = int(self.kwargs['ft'])
            context['tree_id'] = tree_id
        return context

class GenealogyDetailsView(UpdateView, GenealogyContext, LoginRequiredMixin, FormMixin):

    def __init__(self):
        super().__init__()
        self.set_config(APP_FAMILY) #, 'tree')

    def get_success_url(self):
        if ('form_close' in self.request.POST):
            return reverse('family:pedigree-list') + extract_get_params(self.request, None)
        return reverse('family:pedigree-detail', args=(self.object.id,)) + extract_get_params(self.request, None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.config.set_view(self.request)
        upd_context = self.get_app_context(self.request.user.id, icon=self.config.view_icon)
        context.update(upd_context)
        if 'ft' in self.kwargs:
            tree_id = int(self.kwargs['ft'])
            context['tree_id'] = tree_id
        return context

    def tune_dataset(self, data, group):
        return data

           
def photo(request, ft):
    file = get_name_from_request(request, 'file')
    get_object_or_404(FamTreeUser.objects.filter(user_id=request.user.id, tree_id=ft))
    tree = get_object_or_404(FamTree.objects.filter(id=ft))
    media_path = f'{settings.DJANGO_STORAGE_PATH}/family_tree/{tree.store_name()}'
    fsock = open(media_path + '/' + file, 'rb')
    return FileResponse(fsock)

def scaled_image(mmr: MultimediaRecord, size: int) -> HttpResponse:
    file = mmr.get_file() or ''
    store_name = mmr.tree and mmr.tree.store_name() or ''
    media_path = f'{settings.DJANGO_STORAGE_PATH}/family_tree/{store_name}'
    img = Image.open(media_path + '/' + file)
    if mmr._posi:
        box = tuple([int(x) for x in mmr._posi.split(' ')])
        img = img.crop(box)
    thumb_size = (size, size, )
    img.thumbnail(thumb_size)
    format = mmr.get_format()
    response = HttpResponse(content_type='image/' + format)
    img.save(response, format)
    return response

def thumbnail(request, ft, size=44):
    get_object_or_404(FamTreeUser.objects.filter(user_id=request.user.id, tree_id=ft))
    tree = get_object_or_404(FamTree.objects.filter(id=ft))
    mmr_id = get_name_from_request(request, 'mmr')
    mmr = get_object_or_404(MultimediaRecord.objects.filter(id=mmr_id, tree=tree.id))
    if mmr:
        return scaled_image(mmr, size)
    return default_avatar(size)

def thumbnail_100(request, ft):
    return thumbnail(request, ft, 100)

def get_name_from_request(request, param='file'):
    query = ''
    if (request.method == 'GET'):
        query = request.GET.get(param)
    if not query:
        return ''
    return urllib.parse.unquote_plus(query)

@login_required(login_url='account:login')
def avatar(request, ft, pk):
    get_object_or_404(FamTreeUser.objects.filter(user_id=request.user.id, tree_id=ft))
    get_object_or_404(FamTree.objects.filter(id=ft))
    indi = get_object_or_404(IndividualRecord.objects.filter(id=pk))
    mmr = indi.get_avatar_mmr()
    if mmr:
        return scaled_image(mmr, 150)
    return default_avatar(150)

def default_avatar(size: int) -> HttpResponse:
    static_path = settings.DJANGO_STATIC_ROOT
    img = Image.open(static_path + '/Default-avatar.jpg')
    thumb_size = (size, size, )
    img.thumbnail(thumb_size)
    response = HttpResponse(content_type='image/jpeg')
    img.save(response, 'jpeg')
    return response

class UploadGedcomView(FormView, GenealogyContext, LoginRequiredMixin):
    form_class = UploadForm
    file: str

    def __init__(self):
        super().__init__()
        self.file = ''

    def get_success_url(self):
        return reverse_lazy('family:pedigree-import') + '?file=' + self.file

    def post(self, request):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('upload')
        if form.is_valid():
            for f in files:
                self.handle_uploaded_file(request.user, f)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def avoid_duplication(self, f):
        file_parts = os.path.splitext(f)
        file_path = '\\'.join(file_parts[0].split('\\')[:-1])
        file_name = file_parts[0].split('\\')[-1]
        file_name_base = file_name
        file_ext = file_parts[1][1:]
        num = 0
        x = re.fullmatch(r'(.*) \((\d+)\)', file_name)
        if x:
            file_name = x[1]
            num = int(x[2])
        files = glob.glob(file_path + '\\' + file_name + '*.' + file_ext)
        for file in files:
            file_parts = os.path.splitext(file)
            file_name_cmp = file_parts[0].split('\\')[-1]
            if file_name_cmp == file_name_base and num == 0:
                num = 1
            else:
                x = re.fullmatch(r'(.*) \((\d+)\)', file_name_cmp)
                if x:
                    file_name = x[1]
                    if num <= int(x[2]):
                        num = int(x[2]) + 1
        if num == 0:
            return f'{file_path}\\{file_name}.{file_ext}'
        return f'{file_path}\\{file_name} ({num}).{file_ext}'

    def handle_uploaded_file(self, user, f):
        path = FamTree.get_import_path()
        filepath = self.avoid_duplication(path + f.name)
        with open(filepath, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        self.file = filepath.split('\\')[-1]

back/family/views/diagram.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from family.views.base import GenealogyContext
from family.models import Params, UserSettings
from task.const import APP_FAMILY


@login_required(login_url='account:login')
@permission_required('family.view_pedigree')
def diagram_start(request):
    cur_tree = Params.get_cur_tree(request.user)
    if not cur_tree:
        return HttpResponseRedirect(reverse('family:pedigree-list'))
    cur_indi = UserSettings.get_sel_indi(request.user, cur_tree)
    if not cur_indi:
        return HttpResponseRedirect(reverse('family:pedigree-list'))
    return HttpResponseRedirect(reverse('family:diagram', args=(cur_tree.id,)) + f'#/@I{cur_indi.id}@')

@login_required(login_url='account:login')
@permission_required('family.view_pedigree')
def diagram(request, tree_id):
    ctx = GenealogyContext()
    ctx.request = request
    ctx.set_config(APP_FAMILY, 'tree')
    ctx.config.set_view(request)
    context = ctx.get_app_context(request.user.id, icon=ctx.config.view_icon)
    tree = Params.get_cur_tree(request.user)
    indi = UserSettings.get_sel_indi(request.user, tree)
    context['cur_tree_id'] = tree.id if tree else None
    context['cur_indi_id'] = indi.id if indi else None
    template = loader.get_template('family/diagram.html')
    return HttpResponse(template.render(context, request))

back/family/templates/family/pedigree/detail.html
{% extends "core/page_content.html" %}
{% load static i18n %}

{% block extrastyle %}
    {{ block.super }}
    <link href="{% static 'core/css/form.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/widgets.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'family/css/family.min.css' %}" rel="stylesheet"> -->
    <link href="{% static 'iziToast/css/iziToast.min.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
    <div class="list-content{% if theme_id %} theme-{{theme_id}}{% endif %}">
        <form method="post" class="item-form px-2" enctype="multipart/form-data" id="article_form" data-item_id="{{ ed_item.id|cut:" " }}">{% csrf_token %}
            {% include "core/form_errors.html" %}
        
            <div class="accordion" id="accordion_Pedigree">
                <!-- Name -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading_Name">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_Name" aria-expanded="true" aria-controls="collapse_Name">
                            <i class="bi-check2-square me-2"></i>
                            {{ pedigree_name }}
                        </button>
                    </h2>
                    <div id="collapse_Name" class="accordion-collapse show" aria-labelledby="heading_Name">
                        <div class="accordion-body">
                            {{ form.name.errors }}{{ form.name.label_tag }}{{ form.name }}
                            <div class="row">
                                <div class="col-auto">{{ form.date.errors }}{{ form.date.label_tag }}{{ form.date }}</div>
                                <div class="col-auto">{{ form.time.errors }}{{ form.time.label_tag }}{{ form.time }}</div>
                            </div>
                            {{ form.file.errors }}{{ form.file.label_tag }}{{ form.file }}
                        </div>
                    </div>
                </div>
                <!-- Source -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading_Source">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_Source" aria-expanded="false" aria-controls="collapse_Source">
                            <i class="bi-check2-square me-2"></i>
                            {{ pedigree_source }}
                        </button>
                    </h2>
                    <div id="collapse_Source" class="accordion-collapse collapse" aria-labelledby="heading_Source">
                        <div class="accordion-body">
                            <div class="row">
                                <div class="col-auto">{{ form.sour.errors }}{{ form.sour.label_tag }}{{ form.sour }}</div>
                                <div class="col-auto">{{ form.sour_vers.errors }}{{ form.sour_vers.label_tag }}{{ form.sour_vers }}</div>
                                <div class="col-auto">{{ form.sour_corp.errors }}{{ form.sour_corp.label_tag }}{{ form.sour_corp }}</div>
                            </div>
                            {{ form.sour_name.errors }}{{ form.sour_name.label_tag }}{{ form.sour_name }}
                            <div class="row">
                                <div class="col-auto">{{ form.sour_data.errors }}{{ form.sour_data.label_tag }}{{ form.sour_data }}</div>
                                <div class="col-auto">{{ form.sour_data_date.errors }}{{ form.sour_data_date.label_tag }}{{ form.sour_data_date }}</div>
                                <div class="col-auto">{{ form.sour_data_corp.errors }}{{ form.sour_data_copr.label_tag }}{{ form.sour_data_copr }}</div>
                            </div>
                            {{ form.dest.errors }}{{ form.dest.label_tag }}{{ form.dest }}
                        </div>
                    </div>
                </div>
                <!-- Info -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading_Info">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_Info" aria-expanded="false" aria-controls="collapse_Info">
                            <i class="bi-check2-square me-2"></i>
                            {{ pedigree_info }}
                        </button>
                    </h2>
                    <div id="collapse_Info" class="accordion-collapse collapse" aria-labelledby="heading_Info">
                        <div class="accordion-body">
                            <div class="row">
                                <div class="col-auto">{{ form.gedc_vers.errors }}{{ form.gedc_vers.label_tag }}{{ form.gedc_vers }}</div>
                                <div class="col-auto">{{ form.gedc_form.errors }}{{ form.gedc_form.label_tag }}{{ form.gedc_form }}</div>
                                <div class="col-auto">{{ form.char_set.errors }}{{ form.char_set.label_tag }}{{ form.char_set }}</div>
                                <div class="col-auto">{{ form.char_vers.errors }}{{ form.char_vers.label_tag }}{{ form.char_vers }}</div>
                            </div>
                            <div class="row">
                                <div class="col-auto">{{ form.lang.errors }}{{ form.lang.label_tag }}{{ form.lang }}</div>
                                <div class="col-auto">{{ form.copr.errors }}{{ form.copr.label_tag }}{{ form.copr }}</div>
                                <div class="col-auto">{{ form.note.errors }}{{ form.note.label_tag }}{{ form.note }}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Extra -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading_Extra">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_Extra" aria-expanded="false" aria-controls="collapse_Extra">
                            <i class="bi-check2-square me-2"></i>
                            {{ pedigree_extra }}
                        </button>
                    </h2>
                    <div id="collapse_Extra" class="accordion-collapse collapse" aria-labelledby="heading_Extra">
                        <div class="accordion-body">
                            <div class="row">
                                <div class="col-auto">{{ form.mh_id.errors }}{{ form.mh_id.label_tag }}{{ form.mh_id }}</div>
                                <div class="col-auto">{{ form.mh_prj_id.errors }}{{ form.mh_prj_id.label_tag }}{{ form.mh_prj_id }}</div>
                                <div class="col-auto">{{ form.mh_rtl.errors }}{{ form.mh_rtl.label_tag }}{{ form.mh_rtl }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-evenly flex-wrap">
                <button type="submit" name="item_save" class="btn btn-primary m-3 bi-save" title="{% trans 'save changes'|capfirst %}">
                    {% trans 'save'|capfirst %}
                </button>
                <button type="submit" name="form_close" class="btn btn-secondary m-3 bi-x" title="{% trans 'close edit form'|capfirst %}">
                    {% trans 'close'|capfirst %}
                </button>
                <div class="btn-group m-3">
                    <button type="button" class="btn btn-primary dropdown-toggle bi-gear" data-bs-toggle="dropdown" aria-expanded="false">
                        {% trans 'service'|capfirst %}
                    </button>
                    <ul class="dropdown-menu">
                        <li><button type="button" name="media_update" class="dropdown-item bi-save" onclick="updateMedia({{ tree_id }})" title="{% trans 'update media files'|capfirst %}">
                            {% trans 'media'|capfirst %}
                        </button></li>
                        <li><button type="button" name="tree_clone" class="dropdown-item bi-files" onclick="treeClone()" title="{% trans 'clone this tree'|capfirst %}">
                            {% trans 'clone'|capfirst %}
                        </button></li>
                        <li><button type="button" name="tree_merge" class="dropdown-item bi-intersect" onclick="treeMerge()" title="{% trans 'merge with another tree'|capfirst %}">
                            {% trans 'merge'|capfirst %}
                        </button></li>
                        <li><a class="dropdown-item bi-cloud-arrow-down" href="{% url 'family:pedigree-export' tree_id %}" title="{% trans 'export tree to GEDCOM-file'|capfirst %}">
                            {% trans 'export'|capfirst %}
                        </a></li>
                        <li><a class="dropdown-item bi-check2-circle" href="{% url 'family:pedigree-examine' tree_id %}" title="{% trans 'check tree'|capfirst %}">
                            {% trans 'check'|capfirst %}
                        </a></li>
                        <li><button type="button" name="item_delete" class="dropdown-item bi-trash" onclick="delItemConfirm('{{config.get_cur_role}}', '{{ban_on_deletion}}', '{{delete_question}} {{title}}?')" title="{% trans 'delete record'|capfirst %}">
                            {% trans 'delete'|capfirst %}
                        </button></li>
                    </ul>
                </div>

            </div>
      
        </div>
    </form>
{% endblock %}

{% block extrascript %}
  {{ block.super }}
  <script src="{% static 'iziToast/js/iziToast.min.js' %}"></script>
  <script src="{% static 'js/family/pedigree.js' %}"></script>
{% endblock %}

back/family/templates/family/pedigree/import.html
{% extends "core/page_content.html" %}
{% load static i18n %}

{% block extrastyle %}
    {{ block.super }}
    <link href="{% static 'family/css/progress.min.css' %}" rel="stylesheet">
    <link href="{% static 'iziToast/css/iziToast.min.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
{% include "core/title.html" %}
<form method="post" enctype="multipart/form-data" id="gedcom_import_form">{% csrf_token %}</form>
  {% include "core/form_errors.html" %}
  {{ form.upload.errors }}
  <input type="file" style="display:none;" id="id_upload" name="upload" onchange="fileSelected()">
  <button type="submit" id="id_submit" name="file_upload" class="d-none"></button>
  <ol class="list-group list-group-numbered">
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="d-flex">
            <div class="bi-circle mx-3"></div>
            <div class="d-none spinner-border spinner-border-sm text-secondary mx-3" role="status">
                <span class="visually-hidden">Importing...</span>
            </div>
            <div class="d-flex flex-wrap">
                <span class="">{% trans 'Import from GEDCOM-file' %}</span>
                <div id="import" class="d-none progress mx-3 my-1" role="progressbar" aria-label="Import from GEDCOM-file" aria-valuenow="0" aria-valuemin="0" aria-valuemax="0">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 0%"></div>
                </div>
            </div>
        </div>
      </div>
      <span class="badge bg-primary rounded-pill"></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="d-flex">
          <div class="bi-circle mx-3"></div>
          <div class="d-none spinner-border spinner-border-sm text-secondary mx-3" role="status">
              <span class="visually-hidden">Saving GEDCOM...</span>
          </div>
          <div class="d-flex flex-wrap">
              <span class="">{% trans 'Saving GEDCOM' %}</span>
              <div id="gedcom" class="progress d-none mx-3 my-1" role="progressbar" aria-label="Saving GEDCOM" aria-valuenow="0" aria-valuemin="0" aria-valuemax="0">
                  <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 0%"></div>
              </div>
          </div>
        </div>
      </div>
      <span class="badge bg-primary rounded-pill"></span>
    </li>
  </ol>
  <p id="examine-result" class="my-3"></p>
  <a href="{% url 'family:pedigree-list' %}" class="btn btn-secondary m-3 bi-x">{% trans 'Return to Pedigree list' %}</a>
  {% endblock %}

{% block extrascript %}
  {{ block.super }}
  <script src="{% static 'iziToast/js/iziToast.min.js' %}"></script>
  <script src="{% static 'family/js/progress.js' %}"></script>
  <script src="{% static 'family/js/import.js' %}"></script>
{% endblock %}

back/family/templates/family/pedigree/list.html
{% extends "core/list.html" %}
{% load static i18n %}

{% block extrastyle %}
    {{ block.super }}
    <!-- <link href="{% static 'family/css/family.min.css' %}" rel="stylesheet"> -->
{% endblock %}

{% block main %}
  {{ block.super }}
{% endblock %}

{% block extrascript %}
  {{ block.super }}
  <script src="{% static 'core/js/uploadFile.js' %}"></script>
{% endblock %}